CREATE SEQUENCE SEQ_PESSOA
				START WITH 100
				INCREMENT BY 1
				NO MINVALUE
				NO MAXVALUE
				CACHE 1;;

CREATE TABLE PESSOA (
	ID BIGINT NOT NULL DEFAULT NEXTVAL('SEQ_PESSOA'::REGCLASS),
	NOME VARCHAR(255) NOT NULL,
	NASCIMENTO DATE NOT NULL
);
ALTER TABLE PESSOA ADD CONSTRAINT PK_PESSOA_ID PRIMARY KEY (ID);
